auto update version script fix

diff --git a/.github/workflows/auto-update.yml b/.github/workflows/auto-update.yml
--- a/.github/workflows/auto-update.yml
+++ b/.github/workflows/auto-update.yml
@@ -143,7 +143,7 @@ jobs:
         run: |
           cd your-repo
           git tag v${{ steps.compare-versions.outputs.new_version }}-test
-          git push origin v${{ steps.compare-versions.outputs.new_version }} || { echo "Failed to push tag"; exit 1; }
+          git push origin v${{ steps.compare-versions.outputs.new_version }}-test || { echo "Failed to push tag"; exit 1; }
           echo "Created and pushed tag v${{ steps.compare-versions.outputs.new_version }}-test for JitPack."
         shell: bash
 
